version: "3.9"  # optional since v1.27.0

services:
  rentals:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    depends_on:
      - db
  db:
    image: "postgres" # use latest official postgres version
    env_file:
      - .env # configure postgres
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_DB=rental
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: